HW2 is completed
buckster12/go_home_work pull request #4
Opened 2020-03-21 18:53 UTC by buckster12

## Домашнее задание №2 «Распаковка строки»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-03-22 08:14 UTC, kulti requested changes
Спасибо за выполненную работу.

В коде есть проблемы с эффективностью. На данном этапе это не очень важно - предлагаю в первую очередь сконцентрироваться на логике работы.

https://otus.ru/teacher-lk/homework/92774/6026/

2020-03-22 08:14 UTC, kulti commented on hw02_unpack_string/unpack.go
> +			i++
Что будет, если `\` последний символ в строке?

2020-03-22 08:14 UTC, kulti commented on hw02_unpack_string/unpack.go
> +	inputSlice := []rune(inputString)
Такое преобразование приведет к аллокации слайса с рунами. Лишние аллокации - это замедление работы программы и нагрузка на GC, т.е. еще большее замедление.

Если нужны руны, то можно итерироваться по строке так: `for i, r := range inputString`.

2020-03-22 08:14 UTC, kulti commented on hw02_unpack_string/unpack.go
> +		stringElement := string(inputSlice[i])
Это тоже аллокация. Почему бы не работать с рунами?

Вижу сравнение, конвертация в цифру из запись в strings.Builder. Все эти операции можно легко сделать с руной.

2020-03-22 09:47 UTC, buckster12 commented on hw02_unpack_string/unpack.go
> +	inputSlice := []rune(inputString)
я сначала делал через range, но не придумал как перепрыгивать циклы, в случае когда  мы экранизируем символы

2020-03-23 06:40 UTC, kulti commented on hw02_unpack_string/unpack.go
> +	inputSlice := []rune(inputString)
Сейчас в работе с экранированием символов ошибка (предыдущий дискашен) - ее в любом случае нужно исправлять. Если получится придумать такое решение, чтобы избавиться от лишних аллокаций, то будет здорово.

2020-03-23 16:49 UTC, kulti approved these changes
Спасибо за проделанную работу. Теперь все корректно. 10/10.

2020-03-23 17:18 UTC, merged